### PR TITLE
Meher changes

### PR DESCRIPTION
**Pull request by zachzundel**

### CODE REVIEW

**Comment by zachzundel** [comment]
No, and it looks like Travis doesn't like it either.

**Comment by zachzundel** [comment]
It's building successfully! I don't think that SBOL Designer would really test the file upload, except to make sure the old thing broke. I'll check it now.

**Comment by zachzundel** [comment]
I can't run the current version of SBOL Designer because it looks like master is broken. @mehersam -- any chance you can run the ZIP tests on this branch? I don't know where they are.

**Comment by cjmyers** [comment]
True.  Better tested with Meher’s project.  Maybe you can ping her about this being ready once it is merged.

**Comment by cjmyers** [comment]
The break is due to using the combinatorial classes not in libSBOLj master yet.  You can checkout the version of SBOLDesigner one commit earlier, and I think it should be working.  @michael13162

**Comment by michael13162** [comment]
Ya, I'll put the latest commit in its own branch.  1 commit earlier does indeed work.

**Pull request merged**
